# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -name ".DS_Store" -type f -delete -print
      - find . -name "core" -type f -delete -print
      - find . -name "node_modules" -type d -print -exec rm -rf {} +
    silent: false

  init:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # pre-commit
      ## pre-commit フック（pre-commit ステージ）をインストール
      - pre-commit install --install-hooks
      ## commit-msg フックをインストール（commitlint 用追加ステージ）
      - pre-commit install --hook-type commit-msg
      # remove system files
      - task remove_system_files
      # キャッシュクリア (skillsの読み込み時にcacheが悪さすることが多い)
      - rm -rf ./.devcontainer/.state/claude/plugins/cache/*
      # npm
      - cd tools/merge_devbox && npm install
    silent: false

  fmt:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - treefmt -vv {{ .CLI_ARGS }}
    silent: false
