# https://taskfile.dev

version: "3"

vars: {}

tasks:
  list:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task --list-all
    silent: true

  remove_system_files:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - find . -name ".DS_Store" -delete -print
    silent: false

  init:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # キャッシュクリア (skillsの読み込み時にcacheが悪さすることが多い)
      - rm -rf ./.claude/plugins/cache/*
      # npm
      - cd utils/generate_devbox && npm install
    silent: false

  fmt:
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - treefmt
    silent: false
